# Name of our workflow
name: Production deploy

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# List of jobs
jobs:
  # Name of the job
  test-and-deploy-to-vercel:
    # Operating system to run on
    runs-on: ubuntu-latest

    # List of steps that make up the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./lab14/testinglab14

      # Run tests
      - name: Run tests
        run: npm test
        working-directory: ./lab14/testinglab14

      # Build the project
      - name: Build project
        run: npm run build
        working-directory: ./lab14/testinglab14

      # Deploy to Vercels
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: WtPgZNbRUgysRq1fsbGqTm55
          vercel-org-id: 6vNH8OEVwOwWFrXzo9O9mIK3
          vercel-project-id: prj_Vuf3eDrQUOT54chvu1vx0mYDOGnH
          working-directory: ./lab14/testinglab14
